version: 0.2

phases:
  build:
    commands:
      - echo Entrando no build phase
      - mvn clean package
    post_build:
      commands:
        - echo Build finalizado com sucesso
artifacts:
  files:
    - target/BankAccountApi.jar
  discard-paths: yes